# Generated by Django 4.2.1 on 2023-07-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0004_product_remove_resinproduct_user_delete_dreamproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=120)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(default='', max_length=122)),
                ('address', models.CharField(default='', max_length=122)),
                ('city', models.CharField(default='', max_length=1000)),
                ('state', models.CharField(default='', max_length=1000)),
                ('zip_code', models.CharField(default='', max_length=1000)),
                ('phone', models.CharField(default='', max_length=122)),
            ],
        ),
    ]
