# Generated by Django 4.2.1 on 2023-07-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0005_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='videogallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='craft/video')),
            ],
        ),
    ]
