# Generated by Django 4.2.1 on 2023-07-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0006_videogallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='videogallery',
        ),
    ]
