# Generated by Django 4.2.1 on 2023-07-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0008_orderupdate_remove_orders_address_orders_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
