# Generated by Django 4.2.1 on 2023-08-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0009_alter_orderupdate_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
