# Generated by Django 4.2.1 on 2023-08-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0010_remove_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(default='', max_length=122)),
                ('phone', models.CharField(default='', max_length=122)),
                ('desc', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
